# Generated by Django 4.2.6 on 2023-12-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0004_cliente_id_usuario_empresa_id_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sector",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
