# Generated by Django 4.2.6 on 2023-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0005_alter_sector_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="contrasena",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="estado",
            field=models.IntegerField(
                choices=[(0, "Inactivo"), (1, "Activo"), (3, "deshabilitado")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_creacion",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="fecha_modificacion",
            field=models.DateField(auto_now=True),
        ),
    ]
