# Generated by Django 4.2.6 on 2024-01-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0007_campanapublicitaria_id_sector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanapublicitaria",
            name="sedan_admisible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
