# Generated by Django 4.2.6 on 2024-01-07 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0008_campanapublicitaria_sedan_admisible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campanapublicitaria",
            name="id_sector",
        ),
    ]
