# Generated by Django 4.2.6 on 2024-01-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0009_remove_campanapublicitaria_id_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanapublicitaria",
            name="id_sector",
            field=models.IntegerField(null=True),
        ),
    ]
