# Generated by Django 4.2.6 on 2024-01-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0010_campanapublicitaria_id_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanapublicitaria",
            name="bus_admisible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="camion_admisible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="camioneta_admisible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="suv_admisible",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
