# Generated by Django 4.2.6 on 2024-01-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0011_campanapublicitaria_bus_admisible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiculo",
            name="color_vehiculo",
            field=models.CharField(max_length=20),
        ),
    ]
