# Generated by Django 4.2.6 on 2024-01-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_aplication", "0013_alter_vehiculo_categoria_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="campanapublicitaria",
            name="cobro_minimo",
            field=models.FloatField(default=0.07),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="correo_responsable",
            field=models.CharField(default="example@gmail.com", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="hora_monetizable_fin",
            field=models.CharField(default="18:00", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="hora_monetizable_inicio",
            field=models.CharField(default="08:00", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="tarifa_max",
            field=models.FloatField(default=0.39),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="tarifa_min",
            field=models.FloatField(default=0.05),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campanapublicitaria",
            name="tipo_brandeo",
            field=models.CharField(
                choices=[("sticker", "Sticker"), ("panel led", "Panel LED")],
                default="Sticker",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campanapublicitaria",
            name="taller_brandeo",
            field=models.CharField(max_length=30),
        ),
    ]
